partner:
  uploadPath: D:/partner/uploadPath
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    urlPrefix: http://partner-project-ichensw.oss-cn-hangzhou.aliyuncs.com
    accessKeyId: xxxxx
    accessKeySecret: xxxxx
    bucketName: partner-project-ichensw
    fileHost: files
spring:
  profiles:
    active: dev
  application:
    name: partner-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner
    username: root
    password: 87906413
  # session失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  devtools:
    restart:
      enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
server:
  port: 8081
  servlet:
    context-path: /api
#logging:
#  level:
#    cn:
#      ichensw:
#        partner:
#          mapper: trace
mybatis-plus:
  #  configuration:
  #    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
